#pulling the mongo package db from hub.docker.com
db:
   #mongo image
   image: mongo
   #exposing the local ports
   ports:
      - "27017:27017"
   #restarting mongo in case it crash
   restart: always
#starting the web application
web:
   #first building the dockerfile to run the instructions
   build: .
   #mapping the local system
   volumes:
      - ./:/app
   #exposing the web port server
   ports:
      - "3000:3000"
   # linking the database
   links:
      - db
   # running the nodemon command
   command: nodemon /app/server.js
